### ISSUE TITLE
Test issue for attachments

### ISSUE THREAD

**Issue by yorikvanhavre** [yorikvanhavre/BIM_Workbench#84]
This is a dummy, test issue to test
1) If we can attach .FCStd files
2) If attachments can be downloaded locally or via the API

**Comment by yorikvanhavre** [comment]
Ok point 1. failed, FCStd files are not permitted

Trying point 2 with an attached image:
![01_planta_terreo](https://user-images.githubusercontent.com/1136856/145994220-c813ec30-4eee-4cdd-84ab-d3a8d817d876.jpg)

**Comment by yorikvanhavre** [comment]
Above image is saved on a github website and has a public link so it can be downloaded.
Trying with a zip file..
[test.FCStd.zip](https://github.com/yorikvanhavre/BIM_Workbench/files/7711484/test.FCStd.zip)
.

**Comment by yorikvanhavre** [comment]
This is a comment posted from ghi

**Comment by luzpaz** [comment]
@yorikvanhavre maybe we can ask github to allow FCStd files to be supported?

**Comment by yorikvanhavre** [comment]
@luzpaz apparently custom filetypes are a paid feature of github, so it's very unlikely they will give us for free... @donovaly has had a look already, but getting ourselves a paid github account seems also unpractical (you need to get one for each collaborator) :roll_eyes:

**Comment by donovaly** [comment]
> @luzpaz apparently custom filetypes are a paid feature of github,

I thought I read about this. Yesterday I had a closer look and it turned out that this is not the case.

> but getting ourselves a paid github account seems also unpractical (you need to get one for each collaborator) 🙄

Reading the GitHub plans:
https://github.com/pricing
it seems so. Then I asked my IT (we use GitLab but it offers more or less the same plans as GitHub) and as I understood it, every "user" does not mean every contributor, but person who can create releases, merges etc.
I also researched a bit in forums and as we have seems already the optimum for projects like us.
However, I might have made mistakes or misunderstood something.

**Comment by yorikvanhavre** [comment]
I'll close this issue because it was just a test issue.
Regarding .FCStd support there is probably little that can be done while we are on github, but let's keep an eye open.
